# Form implementation generated from reading ui file 'PWM_Acquisition_GUI.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import Qt
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *

import experiment_cmds
import cv2


class Ui_Dialog(object):


    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(697, 318)
        self.doubleSpinBox_Exposure = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_Exposure.setGeometry(QtCore.QRect(630, 10, 62, 22))
        self.doubleSpinBox_Exposure.setObjectName("doubleSpinBox_Exposure")
        self.doubleSpinBox_Exposure.setMinimum(2000.00)
        self.doubleSpinBox_Exposure.setMaximum(10000.00)
        self.doubleSpinBox_Exposure.setValue(4000)
        self.doubleSpinBox_Gain = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_Gain.setGeometry(QtCore.QRect(630, 50, 62, 22))
        self.doubleSpinBox_Gain.setObjectName("doubleSpinBox_Gain")
        self.doubleSpinBox_Gain.setMinimum(0)
        self.doubleSpinBox_Gain.setMaximum(1)
        self.doubleSpinBox_Gain.setValue(0)
        self.doubleSpinBox_PWM_Freq = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_PWM_Freq.setGeometry(QtCore.QRect(630, 90, 62, 22))
        self.doubleSpinBox_PWM_Freq.setObjectName("doubleSpinBox_PWM_Freq")
        self.doubleSpinBox_PWM_Freq.setMinimum(1)
        self.doubleSpinBox_PWM_Freq.setMaximum(80)
        self.doubleSpinBox_PWM_Freq.setValue(60)
        self.Cam_Frame = QtWidgets.QFrame(Dialog)
        self.Cam_Frame.setGeometry(QtCore.QRect(20, 20, 441, 221))
        self.Cam_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Cam_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Cam_Frame.setObjectName("Cam_Frame")
        self.pushButton_Acquire_Images = QtWidgets.QPushButton(Dialog)
        self.pushButton_Acquire_Images.setGeometry(QtCore.QRect(250, 250, 101, 23))
        self.pushButton_Acquire_Images.setObjectName("pushButton_Acquire_Images")
        self.pushButton_Stop_Live = QtWidgets.QPushButton(Dialog)
        self.pushButton_Stop_Live.setGeometry(QtCore.QRect(140, 250, 101, 23))
        self.pushButton_Stop_Live.setObjectName("pushButton_Stop_Live")
        self.pushButton_Live = QtWidgets.QPushButton(Dialog)
        self.pushButton_Live.setGeometry(QtCore.QRect(20, 250, 111, 23))
        self.pushButton_Live.setObjectName("pushButton_Live")
        self.label_Exposure = QtWidgets.QLabel(Dialog)
        self.label_Exposure.setGeometry(QtCore.QRect(490, 10, 131, 20))
        self.label_Exposure.setObjectName("label_Exposure")
        self.label_Gain = QtWidgets.QLabel(Dialog)
        self.label_Gain.setGeometry(QtCore.QRect(490, 50, 131, 20))
        self.label_Gain.setObjectName("label_Gain")
        self.label_Frame_Rate = QtWidgets.QLabel(Dialog)
        self.label_Frame_Rate.setGeometry(QtCore.QRect(490, 90, 131, 20))
        self.label_Frame_Rate.setObjectName("label_Frame_Rate")
        self.label_File_Save_Name = QtWidgets.QLabel(Dialog)
        self.label_File_Save_Name.setGeometry(QtCore.QRect(490, 230, 131, 20))
        self.label_File_Save_Name.setObjectName("label_File_Save_Name")
        self.spinBox_ImgNum = QtWidgets.QSpinBox(Dialog)
        self.spinBox_ImgNum.setGeometry(QtCore.QRect(360, 250, 91, 22))
        self.spinBox_ImgNum.setObjectName("spinBox_ImgNum")
        self.spinBox_ImgNum.setMinimum(0)
        self.spinBox_ImgNum.setMaximum(10000)
        self.spinBox_ImgNum.setValue(100)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(490, 260, 201, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_Apply_Settings = QtWidgets.QPushButton(Dialog)
        self.pushButton_Apply_Settings.setGeometry(QtCore.QRect(490, 290, 201, 23))
        self.pushButton_Apply_Settings.setObjectName("pushButton_Apply_Settings")
        self.line_Splitter = QtWidgets.QFrame(Dialog)
        self.line_Splitter.setGeometry(QtCore.QRect(460, -10, 31, 341))
        self.line_Splitter.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_Splitter.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_Splitter.setObjectName("line_Splitter")
        self.progressBar_Runtime = QtWidgets.QProgressBar(Dialog)
        self.progressBar_Runtime.setGeometry(QtCore.QRect(20, 290, 441, 23))
        self.progressBar_Runtime.setProperty("value", 0)
        self.progressBar_Runtime.setObjectName("progressBar_Runtime")
        # self.checkBox_Save_As_Tiff = QtWidgets.QCheckBox(Dialog)
        # self.checkBox_Save_As_Tiff.setGeometry(QtCore.QRect(490, 180, 131, 20))
        # self.checkBox_Save_As_Tiff.setObjectName("checkBox_Save_As_Tiff")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.connect_buttons()

    def connect_buttons(self):

        # switchin bw tiff and mat

        self.pushButton_Acquire_Images.clicked.connect(
             lambda: experiment_cmds.run_experiment_mat(self.spinBox_ImgNum.value(),
                                                        self.lineEdit.text(), "CUSTOM",
                                                        self.doubleSpinBox_Gain.value(),
                                                        int(self.doubleSpinBox_PWM_Freq.value()),
                                                        int(self.doubleSpinBox_Exposure.value())))


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "PWM Experiment"))
        self.pushButton_Acquire_Images.setText(_translate("Dialog", "Acquire Images"))
        self.pushButton_Stop_Live.setText(_translate("Dialog", "Stop Live Feed"))
        self.pushButton_Live.setText(_translate("Dialog", "Live"))
        self.label_Exposure.setText(_translate("Dialog", "Exposure (ms)"))
        self.label_Gain.setText(_translate("Dialog", "Gain"))
        self.label_Frame_Rate.setText(_translate("Dialog", "Frame Rate (FPS)"))
        self.label_File_Save_Name.setText(_translate("Dialog", "File Save Name"))
        self.lineEdit.setText(_translate("Dialog", "Enter File Name, No Spaces"))
        self.pushButton_Apply_Settings.setText(_translate("Dialog", "Apply Settings"))
